apiVersion: v1
kind: Service
metadata:
  name: wiseolap-svc
spec:
  selector:
    app: wise
  ports:
  - name: web
    port: 8888
    targetPort: 8088
    nodePort: 30100
  - name: web-admin
    port: 8889
    targetPort: 9736
    nodePort: 30101
  type: NodePort
  externalTrafficPolicy: Cluster
