apiVersion: v1
kind: Pod
metadata:
  name: wiseolap
  namespace: hyperdata
  labels:
    app: wise
spec:
  containers:
  - name: wiseolapcon
    image: localhost:5000/wiseolap:6.6.1
    envFrom:
    - configMapRef:
        name: cm-wiseolap
    #- secretRef:
    #    name: sec-dev
    command: 
    - "/bin/bash"
    args: ["/root/command1/command1.sh"]
    ports:
    - containerPort: 8088
      name: listener
      protocol: TCP
    - containerPort: 9736
      name: admin
      protocol: TCP
    - containerPort: 22
      name: sshn
      protocol: TCP
    #volumeMounts:
    #- name: host-path
    #  mountPath: /root/test-tmp
    resources:
      requests:
        memory: 4Gi
    #  limits:
    #    memory: 8Gi
    readinessProbe:
      tcpSocket:
        port: 8088
      initialDelaySeconds: 15
      periodSeconds: 20
    livenessProbe:
      tcpSocket:
        port: 8088
      initialDelaySeconds: 100
      periodSeconds: 600
  #volumes:
  #- name : host-path
  #  hostPath:
  #    path: /tmp
  #    type: DirectoryOrCreate
  terminationGracePeriodSeconds: 0
